import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Sidebar from "@/components/layouts/Sidebar";
import ReduxProvider from "@/components/ReduxProvider";
import { TooltipProvider } from "@/components/ui/tooltip"
import MusicPlayer from "@/components/music/MusicPlayer";
import MusicPlayerSmall from "@/components/music/MusicPlayerSmall";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  nav,
}: Readonly<{
  children: React.ReactNode;
  nav: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-white">
        <ReduxProvider>
          <div className="grid grid-cols-12">
            <div className="md:col-span-3 hidden md:block sticky top-0 h-screen bg-black/15">
              <Sidebar />
            </div>
            <div className=" md:col-span-9 col-span-12 md:px-5 md:px-0 bg-black/15">
              <div className=" sticky top-0 h-14 z-40">
                <Header />
              </div>
              <div className="pb-20 px-5">

           <TooltipProvider>{nav}</TooltipProvider>
              </div>
            </div>
          </div>
          <div className=" fixed bottom-0 w-full md:hidden">
            {/* <MusicPlayerSmall /> */}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
